apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: assurreco
type: Opaque
stringData:
  # Changez ces valeurs avant de déployer en production
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "ChangeMe123!"
  MONGO_URI: "mongodb://admin:ChangeMe123!@mongodb-svc:27017/assurreco?authSource=admin"
  MONGODB_URI: "mongodb://admin:ChangeMe123!@mongodb-svc:27017/assurreco?authSource=admin"
