apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: assurreco
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  # ClusterIP (interne uniquement) — le backend y accède via mongodb-svc:27017
  type: ClusterIP
