sonar.projectKey=frontend
sonar.projectName=PI Frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/reports/**,**/*.test.*,**/*.spec.*
sonar.javascript.lcov.reportPaths=reports/coverage/lcov.info
sonar.host.url=http://localhost:9000

sonar.coverage.exclusions=\
  **/main.jsx,\
  **/assets/**,\
  **/styles/**,\
  **/pages/Dashboard.jsx,\
  **/pages/Inbox.jsx,\
  **/pages/MyProfile.jsx,\
  **/pages/hr/**,\
  **/pages/manager/**,\
  **/pages/employee/**,\
  **/pages/superadmin/**,\
  **/pages/skills.jsx,\
  **/pages/CompleteProfile.jsx,\
  **/pages/ChangePassword.jsx,\
  **/pages/ResetPassword.jsx,\
  **/pages/Register.jsx,\
  **/pages/GitHubCallback.jsx,\
  **/pages/MyActivities.jsx,\
  **/pages/Activities.jsx,\
  **/pages/Competences.jsx,\
  **/pages/Notifications.jsx,\
  **/pages/Teams.jsx,\
  **/pages/Users.jsx,\
  **/pages/Roles.jsx,\
  **/components/FaceLogin.jsx,\
  **/components/FaceRegister.jsx,\
  **/components/FingerScrollController.jsx,\
  **/components/KeyboardNavController.jsx,\
  **/components/MicButton.jsx,\
  **/components/AccessibilityMenu.jsx,\
  **/components/AccessibilityWidget.jsx,\
  **/components/RoleRoute.jsx,\
  **/components/RoleSwitcher.jsx,\
  **/components/Sidebar.jsx,\
  **/components/Topbar.jsx,\
  **/layout/**,\
  **/accessibility/**,\
  **/hooks/**,\
  **/api/http.js,\
  **/api/mock.js
