sonar.projectKey=frontend
sonar.projectName=PI Frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/reports/**,**/*.test.*,**/*.spec.*
sonar.javascript.lcov.reportPaths=reports/coverage/lcov.info
sonar.host.url=http://localhost:9000
