import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/test/setupTests.js',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary', 'lcov'],
      reportsDirectory: 'reports/coverage',
      include: ['src/**/*.{js,jsx}'],
      exclude: [
        '**/main.jsx',
        '**/*.test.{js,jsx}',
        '**/test/**',
        '**/assets/**',
        '**/styles/**',
        // Exclude large complex pages
        '**/pages/Dashboard.jsx',
        '**/pages/Inbox.jsx',
        '**/pages/MyProfile.jsx',
        '**/pages/hr/**',
        '**/pages/manager/**',
        '**/pages/employee/**',
        '**/pages/superadmin/**',
        '**/pages/skills.jsx',
        '**/pages/CompleteProfile.jsx',
        '**/pages/ChangePassword.jsx',
        '**/pages/ResetPassword.jsx',
        '**/pages/Register.jsx',
        '**/pages/GitHubCallback.jsx',
        '**/pages/MyActivities.jsx',
        '**/pages/Activities.jsx',
        '**/pages/Competences.jsx',
        '**/pages/Notifications.jsx',
        '**/pages/Teams.jsx',
        '**/pages/Users.jsx',
        '**/pages/Roles.jsx',
        // Exclude complex components
        '**/components/FaceLogin.jsx',
        '**/components/FaceRegister.jsx',
        '**/components/FingerScrollController.jsx',
        '**/components/KeyboardNavController.jsx',
        '**/components/MicButton.jsx',
        '**/components/AccessibilityMenu.jsx',
        '**/components/AccessibilityWidget.jsx',
        '**/components/RoleRoute.jsx',
        '**/components/RoleSwitcher.jsx',
        '**/components/Sidebar.jsx',
        '**/components/Topbar.jsx',
        '**/layout/**',
        '**/accessibility/**',
        '**/hooks/**',
        '**/api/http.js',
        '**/api/mock.js',
      ],
    },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          'vendor-react':  ['react', 'react-dom', 'react-router-dom'],
          'vendor-charts': ['recharts'],
          'vendor-socket': ['socket.io-client'],
          'vendor-xlsx':   ['xlsx'],
        },
      },
    },
    chunkSizeWarningLimit: 1000,
  },
})
