apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: assurreco
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: "smtp.gmail.com:587"
      smtp_from: "AssurReco Alerts <dhia.haddeji@esprit.tn>"
      smtp_auth_username: "dhia.haddeji@esprit.tn"
      smtp_auth_password: "keuxnmmynntcfdqa"
      smtp_require_tls: true

    inhibit_rules:
      - source_matchers:
          - severity="critical"
        target_matchers:
          - severity="warning"
        equal:
          - alertname

    route:
      group_by: ["alertname", "severity"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: email-critical
      routes:
        - matchers:
            - severity="critical"
          receiver: email-critical
        - matchers:
            - severity="warning"
          receiver: email-warning
          repeat_interval: 8h
        - matchers:
            - severity="info"
          receiver: "null"

    receivers:
      - name: "null"
      - name: email-critical
        email_configs:
          - to: "dhia.haddeji@esprit.tn"
            send_resolved: true
            headers:
              Subject: "[CRITICAL] AssurReco: {{ .GroupLabels.alertname }}"
      - name: email-warning
        email_configs:
          - to: "dhia.haddeji@esprit.tn"
            send_resolved: true
            headers:
              Subject: "[WARNING] AssurReco: {{ .GroupLabels.alertname }}"
